#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.13
# In conjunction with Tcl version 8.6
#    May 23, 2018 10:12:13 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import EDCA_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    EDCA_support.set_Tk_var()
    top = EDCA (root)
    EDCA_support.init(root, top)
    root.mainloop()

w = None
def create_EDCA(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    EDCA_support.set_Tk_var()
    top = EDCA (w)
    EDCA_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_EDCA():
    global w
    w.destroy()
    w = None


class EDCA:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("239x652+1008+19")
        top.title("EDCA")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Button1 = Button(top)
        self.Button1.place(relx=0.08, rely=0.03, height=30, width=77)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=EDCA_support.abrir_file)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Open''')

        self.Button2 = Button(top)
        self.Button2.place(relx=0.08, rely=0.4, height=30, width=77)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Start''')
        self.Button2.bind('<Button-1>',lambda e:EDCA_support.startModel(e))

        self.Button3 = Button(top)
        self.Button3.place(relx=0.59, rely=0.4, height=30, width=77)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Stop''')
        self.Button3.bind('<Button-1>',lambda e:EDCA_support.stopModel(e))

        self.Salir = Button(top)
        self.Salir.place(relx=0.59, rely=0.92, height=30, width=77)
        self.Salir.configure(activebackground="#d9d9d9")
        self.Salir.configure(activeforeground="#000000")
        self.Salir.configure(background="#d9d9d9")
        self.Salir.configure(command=EDCA_support.destroy_window)
        self.Salir.configure(disabledforeground="#a3a3a3")
        self.Salir.configure(foreground="#000000")
        self.Salir.configure(highlightbackground="#d9d9d9")
        self.Salir.configure(highlightcolor="black")
        self.Salir.configure(pady="0")
        self.Salir.configure(text='''Close''')

        self.Label1 = Label(top)
        self.Label1.place(relx=0.46, rely=0.03, height=21, width=32)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Step:''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.63, rely=0.04, height=21, width=72)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(anchor=W)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(relief=GROOVE)
        self.Label2.configure(text='''0''')
        self.Label2.configure(textvariable=EDCA_support.stepCounter)

        self.BSalva = Button(top)
        self.BSalva.place(relx=0.59, rely=0.45, height=30, width=77)
        self.BSalva.configure(command=EDCA_support.salvaModelo)
        self.BSalva.configure(activebackground="#d9d9d9")
        self.BSalva.configure(activeforeground="#000000")
        self.BSalva.configure(background="#d9d9d9")
        self.BSalva.configure(disabledforeground="#a3a3a3")
        self.BSalva.configure(foreground="#000000")
        self.BSalva.configure(highlightbackground="#d9d9d9")
        self.BSalva.configure(highlightcolor="black")
        self.BSalva.configure(pady="0")
        self.BSalva.configure(text='''Save''')
        #self.BSalva.bind('<Button-1>',lambda e:EDCA_support.salvaModelo(e))

        self.BSnap = Button(top)
        self.BSnap.place(relx=0.59, rely=0.50, height=30, width=77)
        self.BSnap.configure(command=EDCA_support.snapShot)
        self.BSnap.configure(activebackground="#d9d9d9")
        self.BSnap.configure(activeforeground="#000000")
        self.BSnap.configure(background="#d9d9d9")
        self.BSnap.configure(disabledforeground="#a3a3a3")
        self.BSnap.configure(foreground="#000000")
        self.BSnap.configure(highlightbackground="#d9d9d9")
        self.BSnap.configure(highlightcolor="black")
        self.BSnap.configure(pady="0")
        self.BSnap.configure(text='''Snap''')

        self.Label4 = Label(top)
        self.Label4.place(relx=0.54, rely=0.1, height=21, width=36)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(activeforeground="black")
        self.Label4.configure(background="#d9d9d9")
        self.Label4.configure(disabledforeground="#a3a3a3")
        self.Label4.configure(foreground="#000000")
        self.Label4.configure(highlightbackground="#d9d9d9")
        self.Label4.configure(highlightcolor="black")
        self.Label4.configure(text='''Scale:''')

        self.Spinbox2 = Spinbox(top, from_=1.0, to=100.0)
        self.Spinbox2.place(relx=0.25, rely=0.1, relheight=0.03, relwidth=0.27)
        self.Spinbox2.configure(activebackground="#f9f9f9")
        self.Spinbox2.configure(background="white")
        self.Spinbox2.configure(buttonbackground="#d9d9d9")
        self.Spinbox2.configure(disabledforeground="#a3a3a3")
        self.Spinbox2.configure(font=font9)
        self.Spinbox2.configure(foreground="black")
        self.Spinbox2.configure(from_="1.0")
        self.Spinbox2.configure(highlightbackground="black")
        self.Spinbox2.configure(highlightcolor="black")
        self.Spinbox2.configure(insertbackground="black")
        self.Spinbox2.configure(selectbackground="#c4c4c4")
        self.Spinbox2.configure(selectforeground="black")
        self.Spinbox2.configure(textvariable=EDCA_support.intervalo)
        self.Spinbox2.configure(to="100.0")
        self.value_list = [0.001,0.002,0.005,0.01,0.02,0.05,0.1,0.2,0.5,1.0,2,]
        self.Spinbox2.configure(values=self.value_list)

        self.Label5 = Label(top)
        self.Label5.place(relx=0.06, rely=0.1, height=21, width=44)
        self.Label5.configure(activebackground="#f9f9f9")
        self.Label5.configure(activeforeground="black")
        self.Label5.configure(background="#d9d9d9")
        self.Label5.configure(disabledforeground="#a3a3a3")
        self.Label5.configure(foreground="#000000")
        self.Label5.configure(highlightbackground="#d9d9d9")
        self.Label5.configure(highlightcolor="black")
        self.Label5.configure(text='''Interval:''')

        self.Label6 = Label(top)
        self.Label6.place(relx=0.71, rely=0.1, height=21, width=52)
        self.Label6.configure(activebackground="#f9f9f9")
        self.Label6.configure(activeforeground="black")
        self.Label6.configure(background="#d9d9d9")
        self.Label6.configure(disabledforeground="#a3a3a3")
        self.Label6.configure(foreground="#000000")
        self.Label6.configure(highlightbackground="#d9d9d9")
        self.Label6.configure(highlightcolor="black")
        self.Label6.configure(relief=GROOVE)
        self.Label6.configure(text='''1''')
        self.Label6.configure(textvariable=EDCA_support.spinbox)

        self.Label7 = Label(top)
        self.Label7.place(relx=0.38, rely=0.15, height=21, width=67)
        self.Label7.configure(activebackground="#f9f9f9")
        self.Label7.configure(activeforeground="black")
        self.Label7.configure(background="#d9d9d9")
        self.Label7.configure(disabledforeground="#a3a3a3")
        self.Label7.configure(foreground="#000000")
        self.Label7.configure(highlightbackground="#d9d9d9")
        self.Label7.configure(highlightcolor="black")
        self.Label7.configure(text='''Population:''')

        self.Label8 = Label(top)
        self.Label8.place(relx=0.67, rely=0.15, height=21, width=64)
        self.Label8.configure(activebackground="#f9f9f9")
        self.Label8.configure(activeforeground="black")
        self.Label8.configure(background="#d9d9d9")
        self.Label8.configure(disabledforeground="#a3a3a3")
        self.Label8.configure(foreground="#000000")
        self.Label8.configure(highlightbackground="#d9d9d9")
        self.Label8.configure(highlightcolor="black")
        self.Label8.configure(relief=GROOVE)
        self.Label8.configure(text='''Label''')
        self.Label8.configure(textvariable=EDCA_support.population)

        self.Ene1 = Label(top)
        self.Ene1.place(relx=0.38, rely=0.2, height=21, width=67)
        self.Ene1.configure(activebackground="#f9f9f9")
        self.Ene1.configure(activeforeground="black")
        self.Ene1.configure(background="#d9d9d9")
        self.Ene1.configure(disabledforeground="#a3a3a3")
        self.Ene1.configure(foreground="#000000")
        self.Ene1.configure(highlightbackground="#d9d9d9")
        self.Ene1.configure(highlightcolor="black")
        self.Ene1.configure(anchor=W)
        self.Ene1.configure(text='''Energy:''')

        self.Ene2 = Label(top)
        self.Ene2.place(relx=0.67, rely=0.2, height=21, width=64)
        self.Ene2.configure(activebackground="#f9f9f9")
        self.Ene2.configure(activeforeground="black")
        self.Ene2.configure(background="#d9d9d9")
        self.Ene2.configure(disabledforeground="#a3a3a3")
        self.Ene2.configure(foreground="#000000")
        self.Ene2.configure(highlightbackground="#d9d9d9")
        self.Ene2.configure(highlightcolor="black")
        self.Ene2.configure(relief=GROOVE)
        self.Ene2.configure(text='''0''')
        self.Ene2.configure(textvariable=EDCA_support.energy)

        self.HideEnergy = Checkbutton(top)
        self.HideEnergy.place(relx=0.38, rely=0.3, height=21, width=84)
        self.HideEnergy.configure(activebackground="#d9d9d9")
        self.HideEnergy.configure(activeforeground="#000000")
        self.HideEnergy.configure(background="#d9d9d9")
        self.HideEnergy.configure(disabledforeground="#a3a3a3")
        self.HideEnergy.configure(foreground="#000000")
        self.HideEnergy.configure(highlightbackground="#d9d9d9")
        self.HideEnergy.configure(highlightcolor="black")
        self.HideEnergy.configure(text='''Hide Energy''')
        self.HideEnergy.configure(variable=EDCA_support.HEnergy)
        self.HideEnergy.configure(width=131)




if __name__ == '__main__':
    vp_start_gui()



